Create school and cohort models
rubyforgood/stocks-in-the-future pull request #29
Opened 2023-07-30 15:02 UTC by randallreedjr

Resolves #13 

### Description

- Include summary of change and what issue is fixed, including relevant motivation and context.
- Explain the need for any added dependencies for this change.
- How have you tested this?
- Anything else we should know about?

### Type of change

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)
* This change requires a documentation update
* Documentation update

### Screenshots

2023-07-30 15:57 UTC, LizPrescott approved these changes
Thanks for doing this!

2023-07-31 11:32 UTC, garettarrowood commented on app/models/school_year.rb
> +class SchoolYear < ApplicationRecord
Since the school year doesn't actually (and shouldn't) belong to a school, can we call it an AcademicYear instead?

2023-07-31 11:44 UTC, garettarrowood commented on db/migrate/20230730151848_create_cohorts.rb
> +      t.integer :grade, null: false
Just to not confuse this with grades of A,B,C,D,F, etc, could we call this field "grade_level"?

2023-07-31 11:53 UTC, garettarrowood requested changes
See comments above

2023-07-31 13:28 UTC, cflipse commented on app/models/school_year.rb
> +class SchoolYear < ApplicationRecord
+1

2023-08-02 14:43 UTC, garettarrowood commented
@randallreedjr - Do you think you'll be able to get back to this this week? And if not, are you cool with me just pulling what you've done so far and applying the last changes suggested above?

2023-08-02 15:50 UTC, randallreedjr commented
> @randallreedjr - Do you think you'll be able to get back to this this week? And if not, are you cool with me just pulling what you've done so far and applying the last changes suggested above?

@garettarrowood Done!

2023-08-02 16:00 UTC, merged